[2024-08-31T13:44:02.708+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-31T13:44:02.799+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_dag.load manual__2024-08-31T13:43:39.032446+00:00 [queued]>
[2024-08-31T13:44:02.826+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_dag.load manual__2024-08-31T13:43:39.032446+00:00 [queued]>
[2024-08-31T13:44:02.971+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-31T13:44:03.769+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-08-31 13:43:39.032446+00:00
[2024-08-31T13:44:03.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'generate_dag', 'load', 'manual__2024-08-31T13:43:39.032446+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpta4vcy6o']
[2024-08-31T13:44:03.812+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask load
[2024-08-31T13:44:03.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T13:44:03.819+0000] {standard_task_runner.py:72} INFO - Started process 186 to run task
[2024-08-31T13:44:04.139+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_dag.load manual__2024-08-31T13:43:39.032446+00:00 [running]> on host 763d90797398
[2024-08-31T13:44:04.386+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T13:43:39.032446+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T13:43:39.032446+00:00'
[2024-08-31T13:44:04.389+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-31T13:44:04.390+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-31T13:44:04.391+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2024-08-31 13:44:02.800646+00:00
[2024-08-31T13:44:04.391+0000] {logging_mixin.py:190} INFO - Dag name:generate_dag and current dag run status:running
[2024-08-31T13:44:04.392+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-31T13:44:04.410+0000] {base.py:84} INFO - Retrieving connection 'dw_stage'
[2024-08-31T13:44:04.543+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 40, in load
    cursor.execute(insertAccount(), record)
                   ^^^^^^^^^^^^^^^
TypeError: insertAccount() missing 3 required positional arguments: 'accountKey', 'accountName', and 'accountDescription'
[2024-08-31T13:44:04.609+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-31T13:44:04.611+0000] {logging_mixin.py:190} INFO - Task start:2024-08-31 13:44:02.800646+00:00 end:2024-08-31 13:44:04.608926+00:00 duration:1.80828
[2024-08-31T13:44:04.612+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): load> dag:<DAG: generate_dag> dagrun:<DagRun generate_dag @ 2024-08-31 13:43:39.032446+00:00: manual__2024-08-31T13:43:39.032446+00:00, state:running, queued_at: 2024-08-31 13:43:39.084750+00:00. externally triggered: True>
[2024-08-31T13:44:04.613+0000] {logging_mixin.py:190} INFO - Failure caused by insertAccount() missing 3 required positional arguments: 'accountKey', 'accountName', and 'accountDescription'
[2024-08-31T13:44:04.614+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=generate_dag, task_id=load, run_id=manual__2024-08-31T13:43:39.032446+00:00, execution_date=20240831T134339, start_date=20240831T134402, end_date=20240831T134404
[2024-08-31T13:44:04.662+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-31T13:44:04.663+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 78 for task load (insertAccount() missing 3 required positional arguments: 'accountKey', 'accountName', and 'accountDescription'; 186)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 40, in load
    cursor.execute(insertAccount(), record)
                   ^^^^^^^^^^^^^^^
TypeError: insertAccount() missing 3 required positional arguments: 'accountKey', 'accountName', and 'accountDescription'
[2024-08-31T13:44:04.738+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-31T13:44:04.817+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T13:44:04.835+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
