[2024-08-31T11:13:43.139+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-31T11:13:43.159+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T11:13:43.170+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T11:13:43.172+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-31T11:13:43.193+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-08-30 00:00:00+00:00
[2024-08-31T11:13:43.202+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T11:13:43.204+0000] {standard_task_runner.py:72} INFO - Started process 257 to run task
[2024-08-31T11:13:43.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'generate_dag', 'extract', 'scheduled__2024-08-30T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp99s3v0gn']
[2024-08-31T11:13:43.207+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask extract
[2024-08-31T11:13:43.270+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [running]> on host 763d90797398
[2024-08-31T11:13:43.394+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-30T00:00:00+00:00'
[2024-08-31T11:13:43.396+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-31T11:13:43.396+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-31T11:13:43.397+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-08-31 11:13:43.159959+00:00
[2024-08-31T11:13:43.398+0000] {logging_mixin.py:190} INFO - Dag name:generate_dag and current dag run status:running
[2024-08-31T11:13:43.399+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-31T11:13:43.929+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 14, in extract
    res = requests.get(f'https://demodata.grapecity.com/contoso/api/v1/accounts?PageNumber={pageNumber}&PageSize=100')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
[2024-08-31T11:13:44.006+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-31T11:13:44.007+0000] {logging_mixin.py:190} INFO - Task start:2024-08-31 11:13:43.159959+00:00 end:2024-08-31 11:13:44.005688+00:00 duration:0.845729
[2024-08-31T11:13:44.008+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): extract> dag:<DAG: generate_dag> dagrun:<DagRun generate_dag @ 2024-08-30 00:00:00+00:00: scheduled__2024-08-30T00:00:00+00:00, state:running, queued_at: 2024-08-31 11:13:11.365665+00:00. externally triggered: False>
[2024-08-31T11:13:44.009+0000] {logging_mixin.py:190} INFO - Failure caused by HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
[2024-08-31T11:13:44.010+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=generate_dag, task_id=extract, run_id=scheduled__2024-08-30T00:00:00+00:00, execution_date=20240830T000000, start_date=20240831T111343, end_date=20240831T111344
[2024-08-31T11:13:44.027+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-31T11:13:44.028+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task extract (HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))); 257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 14, in extract
    res = requests.get(f'https://demodata.grapecity.com/contoso/api/v1/accounts?PageNumber={pageNumber}&PageSize=100')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='demodata.grapecity.com', port=443): Max retries exceeded with url: /contoso/api/v1/accounts?PageNumber=1&PageSize=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
[2024-08-31T11:13:44.065+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-31T11:13:44.150+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T11:13:44.160+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-31T13:44:13.040+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-31T13:44:13.238+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T13:44:13.265+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T13:44:13.274+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-31T13:44:13.411+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-08-30 00:00:00+00:00
[2024-08-31T13:44:13.496+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'generate_dag', 'extract', 'scheduled__2024-08-30T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpyawk9b31']
[2024-08-31T13:44:13.506+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask extract
[2024-08-31T13:44:13.524+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T13:44:13.526+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2024-08-31T13:44:13.840+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_dag.extract scheduled__2024-08-30T00:00:00+00:00 [running]> on host 763d90797398
[2024-08-31T13:44:14.506+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-30T00:00:00+00:00'
[2024-08-31T13:44:14.509+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-31T13:44:14.510+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-31T13:44:14.511+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-08-31 13:44:13.239404+00:00
[2024-08-31T13:44:14.512+0000] {logging_mixin.py:190} INFO - Dag name:generate_dag and current dag run status:running
[2024-08-31T13:44:14.513+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-31T13:44:15.624+0000] {python.py:240} INFO - Done. Returned value was: [{"accountKey":1,"parentAccountKey":null,"accountLabel":"100000","accountName":"Profit and Loss after tax","accountDescription":"Profit and Loss after tax","accountType":null,"operator":null,"customMembers":null,"valueType":null,"customMemberOptions":null,"etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":2,"parentAccountKey":24,"accountLabel":"111000","accountName":"Income","accountDescription":"Income","accountType":"Income","operator":"+","customMembers":null,"valueType":"Income","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":3,"parentAccountKey":24,"accountLabel":"112000","accountName":"Expense","accountDescription":"Expense","accountType":"Expense","operator":"-","customMembers":null,"valueType":"Expense","customMemberOptions":"-","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":4,"parentAccountKey":2,"accountLabel":"110100","accountName":"Sale Revenue","accountDescription":"Sale Revenue","accountType":"Income","operator":"+","customMembers":null,"valueType":"Income","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":5,"parentAccountKey":3,"accountLabel":"112100","accountName":"Cost of Goods Sold","accountDescription":"Cost of Goods Sold","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":6,"parentAccountKey":3,"accountLabel":"112200","accountName":"Selling, General & Administrative Expenses","accountDescription":"Selling, General & Administrative Expenses","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":7,"parentAccountKey":6,"accountLabel":"112300","accountName":"Administration Expense","accountDescription":"Administration Expense","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":8,"parentAccountKey":6,"accountLabel":"112400","accountName":"IT Cost","accountDescription":"IT Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":9,"parentAccountKey":6,"accountLabel":"112500","accountName":"Human Capital","accountDescription":"Human Capital","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":10,"parentAccountKey":6,"accountLabel":"112600","accountName":"Light, Heat, Communication Cost","accountDescription":"Light, Heat, Communication Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":11,"parentAccountKey":6,"accountLabel":"112700","accountName":"Property Costs","accountDescription":"Property Costs","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":12,"parentAccountKey":6,"accountLabel":"112800","accountName":"Other Expenses","accountDescription":"Other Expenses","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":13,"parentAccountKey":6,"accountLabel":"112900","accountName":"Marketing Cost","accountDescription":"Marketing & Advertisement Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":14,"parentAccountKey":13,"accountLabel":"112910","accountName":"Holiday Ad Cost","accountDescription":"Holiday Ad Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":15,"parentAccountKey":13,"accountLabel":"112920","accountName":"Spring Ad Cost","accountDescription":"Spring Ad Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":16,"parentAccountKey":13,"accountLabel":"112930","accountName":"Back-to-School Ad Cost","accountDescription":"Back-to-School Ad Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":17,"parentAccountKey":13,"accountLabel":"112940","accountName":"Business Ad Cost","accountDescription":"Business Ad Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":18,"parentAccountKey":13,"accountLabel":"112950","accountName":"Tax Time / Summer Ad Cost","accountDescription":"Tax Time / Summer Ad Cost","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":19,"parentAccountKey":1,"accountLabel":"131000","accountName":"Taxation","accountDescription":"Taxation","accountType":"Taxation","operator":"-","customMembers":null,"valueType":"Taxation","customMemberOptions":"-","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":20,"parentAccountKey":14,"accountLabel":"112911","accountName":"Radio & TV","accountDescription":"Holiday Ad Cost by Radio & TV","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":21,"parentAccountKey":14,"accountLabel":"112912","accountName":"Print","accountDescription":"Holiday Ad Cost by Print","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":22,"parentAccountKey":14,"accountLabel":"112913","accountName":"Internet","accountDescription":"Holiday Ad Cost by Internet","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":23,"parentAccountKey":14,"accountLabel":"112914","accountName":"Other","accountDescription":"Holiday Ad Cost by Other","accountType":"Expense","operator":"+","customMembers":null,"valueType":"Expense","customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"},{"accountKey":24,"parentAccountKey":1,"accountLabel":"110000","accountName":"Profit and Loss before tax","accountDescription":"Profit and Loss before tax","accountType":null,"operator":"+","customMembers":null,"valueType":null,"customMemberOptions":"+","etlloadId":1,"loadDate":"2009-08-17T20:45:00","updateDate":"2009-08-17T20:45:00"}]
[2024-08-31T13:44:15.762+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-31T13:44:15.766+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=generate_dag, task_id=extract, run_id=scheduled__2024-08-30T00:00:00+00:00, execution_date=20240830T000000, start_date=20240831T134413, end_date=20240831T134415
[2024-08-31T13:44:15.821+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-31T13:44:15.833+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-31T13:44:15.834+0000] {logging_mixin.py:190} INFO - Dag name:generate_dag queued_at:2024-08-31 13:43:41.238955+00:00
[2024-08-31T13:44:15.839+0000] {logging_mixin.py:190} INFO - Task hostname:763d90797398 operator:_PythonDecoratedOperator
[2024-08-31T13:44:15.894+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-31T13:44:16.000+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-31T13:44:16.030+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
