[2024-08-31T12:25:37.383+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-31T12:25:37.433+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_dag.transformation manual__2024-08-31T12:25:30.436481+00:00 [queued]>
[2024-08-31T12:25:37.468+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_dag.transformation manual__2024-08-31T12:25:30.436481+00:00 [queued]>
[2024-08-31T12:25:37.477+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-31T12:25:37.544+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): transformation> on 2024-08-31 12:25:30.436481+00:00
[2024-08-31T12:25:37.555+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=841) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T12:25:37.557+0000] {standard_task_runner.py:72} INFO - Started process 843 to run task
[2024-08-31T12:25:37.560+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'generate_dag', 'transformation', 'manual__2024-08-31T12:25:30.436481+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpnii7k5vw']
[2024-08-31T12:25:37.563+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask transformation
[2024-08-31T12:25:37.691+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_dag.transformation manual__2024-08-31T12:25:30.436481+00:00 [running]> on host 763d90797398
[2024-08-31T12:25:37.883+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_dag' AIRFLOW_CTX_TASK_ID='transformation' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T12:25:30.436481+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T12:25:30.436481+00:00'
[2024-08-31T12:25:37.885+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-31T12:25:37.886+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-31T12:25:37.886+0000] {logging_mixin.py:190} INFO - Current task name:transformation state:running start_date:2024-08-31 12:25:37.434693+00:00
[2024-08-31T12:25:37.887+0000] {logging_mixin.py:190} INFO - Dag name:generate_dag and current dag run status:running
[2024-08-31T12:25:37.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-31T12:25:37.889+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 31, in transformation
    transformed_data.append(accountKey,accountName,accountDescription )
TypeError: list.append() takes exactly one argument (3 given)
[2024-08-31T12:25:37.906+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-31T12:25:37.907+0000] {logging_mixin.py:190} INFO - Task start:2024-08-31 12:25:37.434693+00:00 end:2024-08-31 12:25:37.905737+00:00 duration:0.471044
[2024-08-31T12:25:37.908+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): transformation> dag:<DAG: generate_dag> dagrun:<DagRun generate_dag @ 2024-08-31 12:25:30.436481+00:00: manual__2024-08-31T12:25:30.436481+00:00, state:running, queued_at: 2024-08-31 12:25:30.460579+00:00. externally triggered: True>
[2024-08-31T12:25:37.908+0000] {logging_mixin.py:190} INFO - Failure caused by list.append() takes exactly one argument (3 given)
[2024-08-31T12:25:37.909+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=generate_dag, task_id=transformation, run_id=manual__2024-08-31T12:25:30.436481+00:00, execution_date=20240831T122530, start_date=20240831T122537, end_date=20240831T122537
[2024-08-31T12:25:37.924+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-31T12:25:37.925+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 61 for task transformation (list.append() takes exactly one argument (3 given); 843)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mydag.py", line 31, in transformation
    transformed_data.append(accountKey,accountName,accountDescription )
TypeError: list.append() takes exactly one argument (3 given)
[2024-08-31T12:25:37.952+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-31T12:25:37.980+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T12:25:37.989+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
